//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Book
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Book()
    {
        this.Carts = new HashSet<Cart>();
    }

    public int ID { get; set; }
    public int CatID { get; set; }
    public string Title { get; set; }
    public Nullable<int> Price { get; set; }
    public string Description { get; set; }
    public string CoverArt { get; set; }
    public Nullable<int> Quantity { get; set; }

    public virtual BookCat BookCat { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Cart> Carts { get; set; }
}

public partial class BookCat
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public BookCat()
    {
        this.Books = new HashSet<Book>();
    }

    public int Id { get; set; }
    public string Title { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Book> Books { get; set; }
}

public partial class Cart
{
    public int ID { get; set; }
    public string CustomerID { get; set; }
    public int BookID { get; set; }
    public int Amount { get; set; }
    public Nullable<System.DateTime> DatePurchased { get; set; }
    public bool IsInCart { get; set; }

    public virtual Book Book { get; set; }
}

public partial class UserInfo
{
    public int ID { get; set; }
    public string GUID { get; set; }
    public string ForeName { get; set; }
    public string SurName { get; set; }
    public string Address { get; set; }
    public int PostalCode { get; set; }
}
